// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tytppbzfvlmwdktrgdpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR5dHBwYnpmdmxtd2RrdHJnZHBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NjMyOTksImV4cCI6MjA2MjUzOTI5OX0.U0T2fWourzUy8TYI-N9mlX-WcWAS6fb-uo-gTc4qMSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);